# Generated by Django 4.0.3 on 2022-04-14 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('diameter', models.CharField(max_length=255)),
                ('rotation_period', models.CharField(max_length=255)),
                ('orbital_period', models.CharField(max_length=255)),
                ('gravity', models.CharField(max_length=32)),
                ('population', models.CharField(max_length=255)),
                ('climate', models.CharField(max_length=128)),
                ('terrain', models.CharField(max_length=128)),
                ('surface_water', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=64)),
                ('starship_class', models.CharField(max_length=64)),
                ('manufacturer', models.CharField(max_length=128, null=True)),
                ('cost_in_credits', models.CharField(max_length=255)),
                ('length', models.CharField(max_length=255)),
                ('crew', models.CharField(max_length=255)),
                ('passengers', models.CharField(max_length=255)),
                ('max_atmosphering_speed', models.CharField(max_length=255)),
                ('hyperdrive_rating', models.CharField(max_length=255)),
                ('MGLT', models.CharField(max_length=255)),
                ('cargo_capacity', models.CharField(max_length=255)),
                ('consumables', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('birth_year', models.CharField(max_length=7)),
                ('eye_color', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=16)),
                ('hair_color', models.CharField(max_length=128)),
                ('height', models.CharField(max_length=16)),
                ('mass', models.CharField(max_length=16)),
                ('skin_color', models.CharField(max_length=128)),
                ('species', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('homeworld', models.ManyToManyField(to='api.planet')),
                ('starships', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.starship')),
            ],
        ),
    ]
