# Generated by Django 4.0.3 on 2022-04-15 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_planet_residents_planet_residents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='homeworld',
            field=models.ManyToManyField(null=True, to='api.planet'),
        ),
        migrations.AlterField(
            model_name='person',
            name='species',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='starships',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.starship'),
        ),
    ]
