# Generated by Django 4.0.3 on 2022-04-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_person_homeworld_alter_person_species_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='starships',
        ),
        migrations.AddField(
            model_name='person',
            name='starships',
            field=models.ManyToManyField(null=True, to='api.starship'),
        ),
    ]
