# Generated by Django 4.0.3 on 2022-04-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_person_starships_person_starships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='homeworld',
            field=models.ManyToManyField(blank=True, null=True, to='api.planet'),
        ),
    ]
