# Generated by Django 4.0.3 on 2022-04-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_person_homeworld'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='species',
        ),
    ]
