# Generated by Django 4.0.3 on 2022-04-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_planet_gravity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='homeworld',
            field=models.ManyToManyField(blank=True, to='api.planet'),
        ),
        migrations.AlterField(
            model_name='person',
            name='starships',
            field=models.ManyToManyField(blank=True, to='api.starship'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='residents',
            field=models.ManyToManyField(blank=True, to='api.person'),
        ),
    ]
