# Generated by Django 4.0.4 on 2022-04-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_person_homeworld_alter_person_starships_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='residents',
            field=models.ManyToManyField(blank=True, related_name='resident_in_planet', to='api.person'),
        ),
    ]
