# Generated by Django 4.0.4 on 2022-04-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_planet_residents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='residents',
            field=models.ManyToManyField(blank=True, to='api.person'),
        ),
    ]
