version: "3.8"
services:
  starwars-frontend:
    build:
      context: .
    volumes:
      - .:/frontend/node_modules
    ports:
      - 3000:3000
    image: starwars:frontend
    container_name: starwars-frontend
    command: npm start