jobs:
  include:
    - language: python
      python:
        - "3.10"
        - "3.10.2"
      dist: focal
      before_script:
        - cd backend/
      install:
        - pip install -r requirements.txt
      script:
        - echo "$TRAVIS_EVENT_TYPE"
        - echo "$DIST"
        - lsb_release -a
        - python --version
        - python manage.py test

    - language: node_js
      node_js:
        - "16.14.2"
      cache: npm
      before_install:
        - "npm config set spin false"
      before_script:
        - cd frontend/
      install:
        - npm install
      script:
        - npm test
        - npm run build
