jobs:
  include:
    - language: python
      python:
        - "3.10"
        - "3.10.2"
      dist: focal
      install:
        - cd backend/
        - pip install -r requirements.txt
      script:
        - echo "$TRAVIS_EVENT_TYPE"
        - echo "$DIST"
        - lsb_release -a
        - python --version
        - python manage.py test

    - language: node_js
      node_js:
        - "16.14.2"
      cache:
        directories:
          - frontend/node_modules
      install:
        - cd frontend/
        - npm install
      script:
        - npm run build
